const DEFAULT_SPEED = 10000;

export const TICK_SPEED = {
  NORMAL: 'NORMAL',
  FAST: 'FAST',
  FASTER: 'FASTER',
  FASTEST: 'FASTEST',
  LUDICROUS: 'LUDICROUS',
};

export const TICK_SPEED_DIVISOR = {
  NORMAL: 1,
  FAST: 2,
  FASTER: 5,
  FASTEST: 10,
  LUDICROUS: 100,
};

export const TICK_SPEED_RATE = {
  NORMAL: DEFAULT_SPEED,
  FAST: DEFAULT_SPEED / TICK_SPEED_DIVISOR.FAST,
  FASTER: DEFAULT_SPEED / TICK_SPEED_DIVISOR.FASTER,
  FASTEST: DEFAULT_SPEED / TICK_SPEED_DIVISOR.FASTEST,
  LUDICROUS: DEFAULT_SPEED / TICK_SPEED_DIVISOR.LUDICROUS
};

export const TICK_SPEED_LIST = [
  TICK_SPEED.NORMAL,
  TICK_SPEED.FAST,
  TICK_SPEED.FASTER,
  TICK_SPEED.FASTEST,
  TICK_SPEED.LUDICROUS,
];

export const DAYS_IN_WORLD_YEAR = 365;

export const SEASON = {
  SPRING: 'Spring',
  SUMMER: 'Summer',
  AUTUMN: 'Autumn',
  WINTER: 'Winter'
};

export const SEASON_RANGE = {
  [SEASON.SPRING]: [0, 25.0],
  [SEASON.SUMMER]: [25.0, 50.0],
  [SEASON.AUTUMN]: [50.0, 75.0],
  [SEASON.WINTER]: [75.0, 100.0]
};



